version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/ReviewPortal.API"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src/ReviewPortal.Application"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src/ReviewPortal.Infrastructure"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/tests/ReviewPortal.UnitTests"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/tests/ReviewPortal.IntegrationTests"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
