trigger:
- main

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"

steps:
- task: UseDotNet@2
  inputs:
    packageType: "sdk"
    version: "8.x"

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: "restore"
    projects: "ReviewPortal.slnx"

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: "build"
    projects: "ReviewPortal.slnx"
    arguments: "--configuration $(buildConfiguration) --no-restore"

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: "test"
    projects: "ReviewPortal.slnx"
    arguments: "--configuration $(buildConfiguration) --no-build"

- task: DotNetCoreCLI@2
  displayName: "Publish API"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "src/ReviewPortal.API/ReviewPortal.API.csproj"
    arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build"
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact"
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    ArtifactName: "drop"
    publishLocation: "Container"
