<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ReviewPortal-BackEnd-API-3f2d1fe4-fb06-4cff-b665-1ef7c6edc3ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReviewPortal.Application\ReviewPortal.Application.csproj" />
    <ProjectReference Include="..\ReviewPortal.Infrastructure\ReviewPortal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
