<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ReviewPortal-BackEnd-API-3f2d1fe4-fb06-4cff-b665-1ef7c6edc3ec</UserSecretsId>
    <ReviewPortalApplicationBinaryPath Condition="'$(ReviewPortalApplicationBinaryPath)' == ''">..\ReviewPortal.Application\bin\$(Configuration)\net8.0\ReviewPortal.Application.dll</ReviewPortalApplicationBinaryPath>
    <ReviewPortalInfrastructureBinaryPath Condition="'$(ReviewPortalInfrastructureBinaryPath)' == ''">..\ReviewPortal.Infrastructure\bin\$(Configuration)\net8.0\ReviewPortal.Infrastructure.dll</ReviewPortalInfrastructureBinaryPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseBinaryProjectReferences)' != 'true'">
    <ProjectReference Include="..\ReviewPortal.Application\ReviewPortal.Application.csproj" />
    <ProjectReference Include="..\ReviewPortal.Infrastructure\ReviewPortal.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseBinaryProjectReferences)' == 'true'">
    <Reference Include="ReviewPortal.Application">
      <HintPath>$(ReviewPortalApplicationBinaryPath)</HintPath>
    </Reference>
    <Reference Include="ReviewPortal.Infrastructure">
      <HintPath>$(ReviewPortalInfrastructureBinaryPath)</HintPath>
    </Reference>
  </ItemGroup>

</Project>
